[package]
name = "raytracing"
version = "0.1.0"
authors = ["Ryan Zeigler <zeiglerr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
